### PR TITLE
fix assertion for empty values

### PR DESCRIPTION
**Pull request by tchaloupka**
Added new tests which fails currently

### CODE REVIEW

**Comment by atilaneves** [comment]
I'm not sure about this - why would you want to actually send empty values?

**Comment by tchaloupka** [comment]
Well I'm not sure too :)
But it happened to us with generic data acquisition that one of the string field value became empty and server asserts on it.
We've added the check to solve this and I created this PR with a thought that maybe library can handle this instead of just assert.
But I don't know if it's better to let it assert to notify the wrong data input to the caller or make it work by default and potentially cause other problems unnoticed.

**Comment by atilaneves** [comment]
The assert is there if I'm not mistaken because influx didn't like it at all. It makes more sense to stop it before it goes out through the network. It can either be an assert and part of the API's contract or an enforce, but I don't think it should be silently swallowed.

**Comment by tchaloupka** [comment]
Ok, agree, I'll close this then. Better to know about it sooner than later.

**Comment by atrips** [comment]
Hello,
I agree w/ both of you. In my hobby project I am reading data from sensors and sometimes data can be empty (not null). My Influx version doesn't have any problem to store such a data. So for me it is not a problem to handle such a case in app but not in lib. But generally I think there is a use cases that you want write tags only or tags w/ some values having data and some of them empty.

**Pull request closed without merging**
